
services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network
      - payment-processor

  api1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rinha_db
    depends_on:
      - postgres
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped


  api2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rinha_db
    depends_on:
      - postgres
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rinha_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
